---
server:
    install: '1'
    packages: [git]
    timezone: UTC
    locale: nl_NL.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: default, ip: 192.168.33.99, memory: '512', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
nginx:
    install: '1'
    docroot: /var/www/testdeploy/current
    servername: testdeploy.dev
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt]
composer:
    install: '1'

